### ISSUE TITLE
Event SoftKeyboardEvent.SOFT_KEYBOARD_DEACTIVATE, is never called.

### ISSUE THREAD

**Issue by dani2003** [myflashlab/webView-ANE#61] opened 2016-02-13 08:21 UTC
![keyboard](https://cloud.githubusercontent.com/assets/9074902/13026693/85c17bde-d231-11e5-9162-e7abcf8f279e.jpg)
1) click on Stagetext. Result: opens the keyboard
2) click on Rich WebView. Result: The keyboard closes. But the SoftKeyboardEvent.SOFT_KEYBOARD_DEACTIVATE event is never called.

Help me have stopped for a few days, and I do not find the solution.

**Comment by myflashlab** [comment] 2016-02-14 09:55
We will look into this and update you the soonest possible. Thanks.

**Comment by myflashlab** [comment] 2016-02-15 13:12
tested on both Android and iOS and everything works normally and we do receive the dispatches from StageText!

are you sure you are listening to the keyboard event from the StageText instance?

```actionscript
_inputText.addEventListener(SoftKeyboardEvent.SOFT_KEYBOARD_ACTIVATE, onSoftKeyboardActived);
_inputText.addEventListener(SoftKeyboardEvent.SOFT_KEYBOARD_DEACTIVATE, onSoftKeyboardDeactived);
```

**Comment by dani2003** [comment] 2016-02-15 13:32
Yes, I am very sure.
If you click **inside webview, **the SoftKeyboardEvent.SOFT_KEYBOARD_DEACTIVATE event is not called.

The event is called only if you click the Stage or in another movie clip.

**Comment by dani2003** [comment] 2016-02-15 13:59
Watch the video, link: https://youtu.be/aP6m6_ym4Bo

**Comment by myflashlab** [comment] 2016-02-16 06:55
Cool, you're building a chat system in Air. we were working on a very similar project about a month ago :)

Anyway, about the listeners not being dispatched, we tested when opening the webview but after seeing the video clip, I remembered that we faced exactly the same problem when we were working on our chat project. Unfortunately considering that StageText has been build with Adobe itself, we could not find out why the dispatch is missed when the keyboard is removed.

And I'm afraid to say that we have not yet found a solution for that! So, the trick we did to bypass this problem in our own project was to cover the html content with an invisible layout and JS will know when you are touching or clicking inside the RichWebView and as soon as it's detected, it will call the AS3 side.

We used this trick to know when RichWebView is clicked so we could also knew the keyboard from the StageText is closed. I know, it's a messy hack but works at least.

If we ever found a better solution to this keyboard thing, we will surely update you. I'll mark this conversion now so our dev team will notice it.

**Comment by dani2003** [comment] 2016-02-16 08:25
1) You can implement a Touch events in webview.
2) Disable keyboard in webview http://stackoverflow.com/questions/17672116/how-disable-softkeyboard-in-webview ex: RichWebViewSettings.DISABLE_EVENT_KEYBOARD = TRUE;

These methods make the extensions are unique and different from competitors ..

**Comment by dani2003** [comment] 2016-02-16 09:33
Other extensions ( http://airnativeextensions.com/extension/com.distriqt.NativeWebView#about ) already have :
1 ) Touch events
2 ) Prevent keyboard open / close in webview .

Let me know if you have intentions of developing them in the next version , or I have to buy the other extension .

**Comment by myflashlab** [comment] 2016-02-16 09:43
I have already marked this conversion for the dev team to have a closer look and add required enhancements on the board. when we update this, you'll know. Thanks.

**Comment by myflashlab** [comment] 2016-02-21 10:18
V6.1.0 now supports TouchEvent so you will know when the webview content is touched.
About preventing the keyboard from opening/closing in webview, we'd appreciate if you can give us more real world scenarios on when it would be useful?

**Comment by dani2003** [comment] 2016-02-21 10:32
I need to know when the keyboard is closed when you click on a webview.
Watch the video.-> "https://youtu.be/DESjQR7FFIA"
If you click inside webview, the SoftKeyboardEvent.SOFT_KEYBOARD_DEACTIVATE event is not called.

**Comment by dani2003** [comment] 2016-02-22 12:03
Excuse me very much, there is news?
I can not continue if you do not solve this problem.

**Comment by dani2003** [comment] 2016-02-25 16:27
Have disappeared? When this problem will be solved?
How do I know when the keyboard is closed through webview.

**Comment by myflashlab** [comment] 2016-02-26 11:31
When touching on the RichWebView, it will dispatch the touch to the Air and considering that the keyboard closes then, you can use the touch listener, right? 

We are still testing the keyboard listeners. in different scenarios. it's dispatching fine though!

**Comment by dani2003** [comment] 2016-02-26 16:25
The keyboard will close when you click on webview.
The click event is different from the event touches. The event touches, It is used to scroll the page.

I have done a thousand tests. When you click inside webview, the SoftKeyboardEvent.SOFT_KEYBOARD_DEACTIVATE event is never called.
Shows an example where the event is called. Thank you.!

**Comment by dani2003** [comment] 2016-03-01 08:59
Bad support. It's been 17 days since I've reported the problem.
The answers come with a dropper and not say when they will be resolved ...

Go somewhere else .... bye bye!

**Comment by majidHejazi** [comment] 2016-04-27 11:12
After more study on this we came to the conclusion that this is not a bug on the RichWebView. And it can easily be fixed by the following instruction.

What actually happens is that focus is moved from the **StageText** to the **RichWebview** instance when you touch over the webview. So the StageText can't understand when to dispatch the required events. To solve this problem, all you have to do is to set the focus of the stage to ```null```.
```actionscript
stage.focus = null
```

for a more detailed example, do it like below:
```actionscript
_ex.addEventListener(RichWebViewEvent.TOUCH, onTouch);
private function onTouch(e:RichWebViewEvent):void
{
	stage.focus = null;
}
```
As soon as you call that, the StageText keyboard listener will be fired with no problem.
```actionscript
SoftKeyboardEvent.SOFT_KEYBOARD_DEACTIVATE
```

**Closed** 2016-05-16 04:25 UTC
