### ISSUE TITLE
On Android, attempting to type into flash.text.TextField, keyboard does not appear

### ISSUE THREAD

**Issue by galaxybeing** [myflashlab/webView-ANE#60] opened 2016-02-11 20:30 UTC
On Android, attempting to type into an input textfield, keyboard does not appear.  The screen slides up, but not keyboard appears.  We've seen this in every input field in our app.  Seen on Samsung Galaxy Tab 4, Android version: 4.4.2, and verified on Galaxy S III.  The webView is positioned off screen.

![missing keyboard](https://cloud.githubusercontent.com/assets/12906083/12989449/48a9e626-d0cb-11e5-86f0-9d47ffbec84a.png)

**Comment by galaxybeing** [comment] 2016-02-13 05:34
I verified that it is the ANE but avoiding initializing the ANE and just loading the activity.  When you click in a text field to enter text, the screen slides up as abovie, then this keyboard/field screen appears.

![missing keyboard 2](https://cloud.githubusercontent.com/assets/12906083/13026082/d6232b0a-d1e0-11e5-8b6e-0b27c2488ae6.png)

**Comment by myflashlab** [comment] 2016-02-14 09:57
I'm not sure I understood what the problem is exactly. would you please elaborate more on this?

**Comment by galaxybeing** [comment] 2016-02-14 18:10
Without webView ANE, if you tap a Flash input textfield to type into it, a keyboard will appear.  

With the webView ANE instantiated, if you tap a Flash input textfield to type into it, the keyboard does NOT appear, so it is impossible to enter or edit text.  This is only on Android, but it has been verified on two different devices.

**Comment by myflashlab** [comment] 2016-02-15 13:25
Yes, we know. You probably want to report this bug to Adobe though! OR try using StageText instead of TextField class.

**Comment by galaxybeing** [comment] 2016-02-15 14:27
You understand the inner workings a lot more than me and assume I know what is going on under the hood

Now I have to ask the same.  I don't understand.  Can you elaborate?   :-). Why is this not your problem if it only happens when your ANE is present?  

.

**Comment by myflashlab** [comment] 2016-02-16 07:03
I'm not sure if you have happened to use Adobe's StageText instead of the classic TextField class or not but you can consider StageText as Adobe's real solution to support input text in mobile projects. We believe the classic TextField is just their for legacy reasons. 

When RichWebView is present, the keyboard on TextField won't show and we have no way to know why, maybe Adobe can answer that. on the other hand, what we know is that StageText will work in a similar scenario. I recommend to you to start using StageText instead of TextField.

**Comment by galaxybeing** [comment] 2016-02-16 18:28
"Yes, we know. "   So you knew about this issue, yet when I was creating my estimate for my client, I never saw anything about this in your marketing materials or your readme file, so I did't figure it into my estimate.  I don't know that I am going to do now.  

"I recommend to you to start using StageText instead of TextField"  These games/activities where created in AS2 years ago for the web and used TextFields in Flash Pro.  3 years ago we converted them to AS3 and put them all into one mobie app and they worked fine on both iOS and Android.  Well, as best they can.  You can see from the screenshot that in one of them there's a post it note at an angle with a script font and on a PC/Mac you actually edit the script text at an angle.  On mobile it appears to automatically switch to a native text field while you are editing, so you lose the original feel of the interface.  And I looked at StageText and it does not improve on that.  Anyway, TextFields have worked fine on both iOS and Android for the past 3 years and I can't see going through the hassle of using StageText unless it had some feature I required... or I was going to be using it with your RichWebView.

**Comment by galaxybeing** [comment] 2016-02-16 20:32
I figured out a workaround!! Save the url it's on,  kill RichWebView, load the game, edit the field, reload RichWebView and go back to the same page.  Works great!  Hardly any delay to get back to the page.  I could have had this figured out a week ago if you would have just said "we know, we can't fix it.  Adobe."

**Comment by myflashlab** [comment] 2016-02-17 04:11
"Yes, we know" In this sense that we noticed that when another similar question was asked! https://github.com/myflashlab/webView-ANE/issues/61

**Comment by myflashlab** [comment] 2016-05-16 04:28
I know this is related to the classic TextField class and you already have a work around as said in your last message. but I think it's a good idea to link you to [this post](https://github.com/myflashlab/webView-ANE/issues/61#issuecomment-215052184) before closing the ticket. If you have more questions, please open a new ticket. Thanks,

**Closed by myflashlab** 2016-05-16 04:28 UTC
