### ISSUE TITLE
openEmbeddedBrowser returns false on Android 6.0.1

### ISSUE THREAD

**Issue by danyradu** [myflashlab/webView-ANE#165] opened 2017-05-25 12:53 UTC
Air 24, flash builder 4.7, flex sdk 4.6.0

**Comment by AmeenAlHosani** [comment] 2017-08-11 20:02
Hi danyradu,
I have similar issue, did you find out any solution or a hint?
Thanks in advance.

https://github.com/myflashlab/webView-ANE/issues/178

Hi, I am using Flash CS6, I bought RichWebView ANE
Air 25 & 26, android 6.0.1
I followed the instructions on this link
https://github.com/myflashlab/webView-ANE
theApp.apk Demo worked in my device
while testing EmbeddedBrowser (on same android device):
isEmbeddedBrowserInitialized returns true
isEmbeddedBrowserSupported() returns true
_ex.openEmbeddedBrowser("https://www.google.com/") returns false
I don't think that there is a problem with RichWebViewSettings.EMBEDDED_BROWSER parameters

why is openEmbeddedBrowser returning false

I am not using permissionCheck

Ameen Al Hosani
Kind Regards

**Comment by myflashlab** [comment] 2017-08-13 12:22
Please copy paste your current code on how you are trying to open the embedded browser... copy the actionscript side and also your manifest .xml file.

are you missing the following receiver: https://github.com/myflashlab/webView-ANE/blob/master/FD/application.xml#L37
```xml
<receiver android:name="com.doitflash.webView.ChromeTabActionBroadcastReceiver" />
```

or, are you initializing the feature correctly? https://github.com/myflashlab/webView-ANE/blob/master/FD/src/Demo.as#L223

**Comment by AmeenAlHosani** [comment] 2017-08-13 14:32
the receiver was added, yet the issue is still exist
I followed this video tutorial
https://www.youtube.com/watch?v=fhtZw5ZDFMs&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O&index=3
It would be great to have working .fla file even with the demo version of the ANE
the code: (action script in the first frame)
I'm using dynamic text filed and setTimeout to check the ANE
isEmbeddedBrowserInitialized returns true : after 2.5 seconds
isEmbeddedBrowserSupported() returns true
_ex.openEmbeddedBrowser("https://www.google.com/") returns false: after 5 seconds
the delay time just for checking.
```
import com.myflashlab.air.extensions.webView.RichWebView;
import com.myflashlab.air.extensions.webView.RichWebViewEvent;
import com.myflashlab.air.extensions.webView.RichWebViewSettings;

import com.myflashlab.air.extensions.dependency.OverrideAir;
import com.myflashlab.air.extensions.dependency.AndroidSupport;

var _ex:RichWebView;
setTimeout(init, 2500);
setTimeout(init2, 5000);
function init():void{
	// initialize the embedded Browser feature (Custom Tabs on Android and SafariViewController on iOS)
	 _ex= new RichWebView(this.stage);
	 
	// set optional RichWebview settings (apply these settings AFTER initializing the ANE and BEFORE opening a webpage)
	RichWebViewSettings.ENABLE_BITMAP_CAPTURE = true;
	RichWebViewSettings.ENABLE_COOKIES = true;
	RichWebViewSettings.ENABLE_THIRD_PARTY_COOKIES = true;
	RichWebViewSettings.ENABLE_GPS = true;
	RichWebViewSettings.ENABLE_ZOOM = true;
	RichWebViewSettings.ENABLE_SCROLL_BOUNCE = false;
	RichWebViewSettings.BG_COLOR_HEX = "#FFFFFFFF"; // AARRGGBB
	//RichWebViewSettings.USER_AGENT = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.36 (KHTML, like Gecko) Chrome/13.0.766.0 Safari/534.36"; // useful when you are trying to load embedded YouTube or Vimeo videos
	RichWebViewSettings.ENABLE_AIR_PREFIX = true; // This property works on Android ONLY and is set to true by default.
	
	if (!_ex.isEmbeddedBrowserInitialized)
	{
		_ex.addEventListener(RichWebViewEvent.EMBEDDED_BROWSER_NAVIGATION_EVENT, onEmbeddedBrowserNavigationEvent);
		_ex.addEventListener(RichWebViewEvent.EMBEDDED_BROWSER_ACTION, onEmbeddedBrowserAction);
		_ex.initEmbeddedBrowser();
		txt.text=String(_ex.isEmbeddedBrowserInitialized);
	}
	
	// set optional settings for the embedded browser - Android side
	RichWebViewSettings.EMBEDDED_BROWSER.android.toolbarColor = "#3F51B5";
	RichWebViewSettings.EMBEDDED_BROWSER.android.secondaryToolbarColor = "#303F9F";
	RichWebViewSettings.EMBEDDED_BROWSER.android.addMenuItem("item 1", true);
	RichWebViewSettings.EMBEDDED_BROWSER.android.addMenuItem("item 2");
	RichWebViewSettings.EMBEDDED_BROWSER.android.addMenuItem("item 3");
	RichWebViewSettings.EMBEDDED_BROWSER.android.addMenuItem("item 4");
	RichWebViewSettings.EMBEDDED_BROWSER.android.actionButton("ic_default_action_btn_for_custom_tab", "action btn description"); // use the Resource Manager Tool to add the icon into "richWebView.ane"
	RichWebViewSettings.EMBEDDED_BROWSER.android.enableUrlBarHiding = true;
	RichWebViewSettings.EMBEDDED_BROWSER.android.closeBtnIcon = "ic_default_close_btn_for_custom_tab"; // use the Resource Manager Tool to add the icon into "richWebView.ane"
	RichWebViewSettings.EMBEDDED_BROWSER.android.showTitle = true;
	RichWebViewSettings.EMBEDDED_BROWSER.android.defaultShareMenuItem = true;
	RichWebViewSettings.EMBEDDED_BROWSER.android.isWeakActivity = false;
	RichWebViewSettings.EMBEDDED_BROWSER.android.mayLaunchUrl = "https://www.google.com/";
	
	// set optional settings for the embedded browser - iOS side
	//RichWebViewSettings.EMBEDDED_BROWSER.ios.barColor = "#CCCCCC"; // if iOS < 10, nothing happens
	//RichWebViewSettings.EMBEDDED_BROWSER.ios.controlColor = "#AAAAAA"; // if iOS < 10, nothing happens
	
	/*if (_ex.isEmbeddedBrowserSupported())
	{
		// SafariViewController works on iOS9+
		// custom-tabs works on Android devices whith the chrome browser being updated
		
		_ex.openEmbeddedBrowser("https://www.google.com/");
	}*/
}

function init2():void{
	if (_ex.isEmbeddedBrowserSupported())
	{
		// SafariViewController works on iOS9+
		// custom-tabs works on Android devices whith the chrome browser being updated
		
		var result:Boolean =_ex.openEmbeddedBrowser("https://www.google.com/");
		txt.text=String(result);
	}
}

function onEmbeddedBrowserNavigationEvent(e:RichWebViewEvent):void
{
	switch (e.param) 
	{
		case RichWebViewEvent.EMBEDDED_BROWSER_NAVIGATION_STARTED:
			
			trace("EMBEDDED_BROWSER NAVIGATION_STARTED");
			
		break;
		case RichWebViewEvent.EMBEDDED_BROWSER_NAVIGATION_FINISHED:
			
			trace("EMBEDDED_BROWSER NAVIGATION_FINISHED");
			
		break;
		case RichWebViewEvent.EMBEDDED_BROWSER_NAVIGATION_FAILED:
			
			trace("EMBEDDED_BROWSER NAVIGATION_FAILED");
			
		break;
		case RichWebViewEvent.EMBEDDED_BROWSER_NAVIGATION_ABORTED:
			
			trace("EMBEDDED_BROWSER NAVIGATION_ABORTED");
			
		break;
		case RichWebViewEvent.EMBEDDED_BROWSER_CLOSED:
			
			trace("EMBEDDED_BROWSER CLOSED");
			
		break;
		default:
	}
}

function onEmbeddedBrowserAction(e:RichWebViewEvent):void
{
	trace("--------- onEmbeddedBrowserAction ------------");
	trace("item = " + e.param.item);
	trace("url = " + e.param.url);
	trace("----------------------------------------------");
}
```
manifest .xml

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<application xmlns="http://ns.adobe.com/air/application/26.0">
    <id>ameen</id>
    <versionNumber>1.0.0</versionNumber>
    <filename>ameen</filename>
    <description></description>
    <!-- To localize the description, use the following format for the description element.
	<description>
		<text xml:lang="en">English App description goes here</text>
		<text xml:lang="fr">French App description goes here</text>
		<text xml:lang="ja">Japanese App description goes here</text>
	</description>
	-->
    <name>ameen</name>
    <!-- To localize the name, use the following format for the name element.
	<name>
		<text xml:lang="en">English App name goes here</text>
		<text xml:lang="fr">French App name goes here</text>
		<text xml:lang="ja">Japanese App name goes here</text>
	</name>
	-->
    <copyright></copyright>
    <initialWindow>
        <content>ameen.swf</content>
        <systemChrome>standard</systemChrome>
        <transparent>false</transparent>
        <visible>true</visible>
        <fullScreen>true</fullScreen>
        <autoOrients>false</autoOrients>
        <aspectRatio>landscape</aspectRatio>
        <renderMode>direct</renderMode>
    </initialWindow>
    <customUpdateUI>false</customUpdateUI>
    <allowBrowserInvocation>false</allowBrowserInvocation>
    <icon></icon>
    <android>
        <manifestAdditions><![CDATA[
        
        <manifest android:installLocation="auto">
		
		<!--The new Permission thing on Android works ONLY if you are targetting Android SDK 23 or higher-->
		<uses-sdk android:targetSdkVersion="23"/>
		
		<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
		
		<!--required for enabling gps for webview-->
		<uses-permission android:name="android.permission.INTERNET" />
		<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
		
		<application android:hardwareAccelerated="true" android:allowBackup="true">
			<activity android:hardwareAccelerated="true">
				<intent-filter>
					<action android:name="android.intent.action.MAIN" />
					<category android:name="android.intent.category.LAUNCHER" />
				</intent-filter>
				<intent-filter>
					<action android:name="android.intent.action.VIEW" />
					<category android:name="android.intent.category.BROWSABLE" />
					<category android:name="android.intent.category.DEFAULT" />
				</intent-filter>
			</activity>
			
			<!-- required for html file select buttons -->
			<activity android:name="com.doitflash.webView.Pick" android:theme="@style/Theme.Transparent" />
			<receiver android:name="com.doitflash.webView.ChromeTabActionBroadcastReceiver" />
		</application>
		
</manifest>
        
        ]]></manifestAdditions>
    </android>
    <versionLabel></versionLabel>
    <supportedLanguages>en</supportedLanguages>
    <extensions>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
        <extensionID>com.myflashlab.air.extensions.webView</extensionID>
    </extensions>
</application>
```

**Comment by myflashlab** [comment] 2017-08-20 05:48
Please try this demo ane while you are making sure that you are using the latest AndroidStudio/OverrideAir dependencies. 
[richWebView.ane.zip](https://github.com/myflashlab/webView-ANE/files/1236874/richWebView.ane.zip)

if you are still seeing the problem, activate the overrideAir debugging tool as described [here](https://github.com/myflashlab/common-dependencies-ANE/tree/master/overridAir) and send us the logs so we can investigate this even more.

**Comment by AmeenAlHosani** [comment] 2017-08-20 12:16
Thank you very much
the problem is solved using the demo ANE provided
I did not try overrideAir debugging tool, the ANE works fine
please inform when will the update be available
-------
another question: can I change how EmbeddedBrowser appears (slide from right), to just be appeared instead

Ameen Al Hosani
Kind Regards

**Comment by myflashlab** [comment] 2017-08-21 10:21
V7.1.1 is now released with this problem fixed. About changing the animation of how the tab appears, well, this is not something that we had planned and have not tested it but maybe the [RMT](https://github.com/myflashlab/Resource-Manager-AIR) software can help you change the animation layout resources which are currently inside the ANE.

**Closed by myflashlab** 2017-08-21 10:21 UTC
